[build]
  command = "pip install -r requirements.txt && gunicorn wsgi:app"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.10"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 