[build]
  command = "pip install -r requirements.txt && gunicorn wsgi:app"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.10"

[[redirects]]
  from = "/*"
  to = "http://127.0.0.1:8000/:splat"
  status = 200
  force = true

[functions]
  directory = "functions"
  node_bundler = "esbuild" 